docs: Calling method with '()' causes Error (#14832)
Calling method with '()' causes Error:
Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    print(driver.current_window_handle())
TypeError: 'str' object is not callable